debug:
    logging:
        configuration: info
        initialization: debug
        collision_space: info
        kinematics: info
        hashmanager: info
        search: info
        motionprimitives: info
        heuristics: info
        pathpostprocessor: debug
